= DZX-Forth
:author: Marcos Cruz (programandala.net)
:revdate: 2016-03-22

// This file is part of DZX-Forth
// http://programandala.net/en.program.dzx-forth.html

== Description

DZX-Forth is a Forth system under development for
http://www.worldofspectrum.org/zxplus3e[ZX Spectrum +3e].

Home page: http://programandala.net/en.program.dzx-forth.html

== Origin

DZX-Forth was forked from http://dxforth.netbay.com.au/[CP/M DX-Forth]
a Forth-94 system for 8088 CP/M.

The fork was done from DX-Forth 4.00, then updated to DX-Forth 4.09;
also some changes and fixes from versions 4.10 and 4.11 were
incorporated later into DZX-Forth.

== Goal

The first goal was to build a modern Forth system for ZX Spectrum +3
and ZX Spectrum +3e.  But the original +3DOS has an important bug for
a Forth system: it is impossible to know the size of files that don't
have a +3DOS header. Happily this bug, was fixed in ZX Spectrum +3e
v1.37 by its author, Garry Lancaster.  This made ZX Spectrum +3e the
only platform for DZX-Forth.

Support for
http://www.worldofspectrum.org/zxplus3e/idedos.html[IDEDOS] and
http://www.worldofspectrum.org/residos/[ResiDOS] is planned.

== Status

DZX-Forth is a sleeping project. It was developed from 2014-12-30 to
2015-05-20.  It's not finished but it's usable.

Two development problems put the project on stand-by for a while:

- DX-Forth is written for the 8080 processor. Therefore many routines
  are not optimized for the more powerful Z80. This means some code is
  slower and bigger than it could be. Identifying and optimizing those
  parts of the original source was an additional task.
- The kernel of DX-Forth is very big, intended for a 64-KiB RAM space.
  The ZX Spectrum +3e has a similar paging mode, but the goal was to
  fit the system into the 48 KiB of the ordinary paging modes. Moving
  the less used code from the kernel to the library became a problem,
  because many words depend on shared assembly routines, which are not
  accessible outside the kernel without adding new words.

Some code of DZX-Forth has been reused in
http://programandala.net/en.program.solo_forth.html[Solo Forth], a
Forth system with a different approach, under active development, for
ZX Spectrum 128 and G+DOS.

A Git repository for DZX-Forth was created on 2016-03-21 with the
development backups, in order to make future development easier.

== Usage

Two DSK disk images are included in the _bin_ directory.  Note both of
them are double-sided 80-track 760-KiB disk images, not the original
single-sided 40-track 190-KiB format of +3DOS. Your ZX Spectrum
emulator should support them.

Open disk A with your favorite ZX Spectrum emulator.  A launcher is
provided for the Fuse emulator. Open also disk B, which contains
source files.

Example: How to open a blocks file from disk B:

----
s" b:tools.fb" r/o open-block-file
1 load
1 list
----

== Documentation

Documentation is in a very early stage. It mostly consists of the
original documentation of DX-Forth, converted to
http://asciidoctor.org[Asciidoctor] format, and with some changes and
addons.

== Compilation

A Makefile file for `make` is provided.  But at the time of writing
(2016-03-22) compilation is not possible because the Forth tool which
builds the BASIC loader depends on some modules of the
http://programamandala.net/en.program.galope.html[Galope library],
which is not published. This is noted in the Makefile and will be
solved in a future version. Meanwhile, a temporary solution is to edit
the Makefile and comment out the following recipe, provided the
address of the Forth system has not been changed (it's 25000 by
default):

----
dzx-forth_loader.bas : dzx-forth_loader.bas.raw dzx-forth_kernel.tap
	@make dzx-forth_kernel.tap
	./tools/patch_the_loader.fs
----

Requirements of the Makefile:

- http://pasmo.speccy.org/[Pasmo] (by Julián Albo)
- http://www.seasip.info/ZX/unix.html[tap2dsk] from Taptools (by John
  Elliott)
- http://metalbrain.speccy.org/link-eng.htm[bin2code] (by MetalBrain)
- http://worldofspectrum.org[bas2tap] from the utilities section of
  World of Spectrum (by Martijn van der Heide)
- http://gnu.org/software/gforth[Gforth] (by Anton Ertl, Bernd Paysan
  et al.)
- http://asciidoctor.org[Asciidoctor] (by Dan Allen), only to build
  the documentation

Then just do `make` and two updated DSK disk images will be created in
the _bin_ directory. You can build only one of the disks with `make
dsk1` and `make dsk2`.

To build the documentation from the Asciidoctor sources: `make doc`.
