\ DX-Forth layer for DZX-Forth

' NOOP ALIAS -CAPS IMMEDIATE
' NOOP ALIAS CAPS IMMEDIATE
' NOOP ALIAS SYS IMMEDIATE
' NOOP ALIAS SYSTEM IMMEDIATE
' PARSE-NAME ALIAS TOKEN
' WORDLIST>NAME ALIAS W>NAME
' .WID ALIAS .VOC
